[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.6"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
wasm-logger = "0.2.0"
