name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  # build:
  #   runs-on: ubuntu-latest

  #       steps:
  #   - uses: actions/checkout@v1
  #   - name: Setup toolchain
  #     uses: dtolnay/rust-toolchain@master
  #     with:
  #       toolchain: stable
  #       targets: wasm32-unknown-unknown
  #       components: rust-src
  #   - name: Install webkit2gtk for Tauri
  #     run: |
  #      sudo apt update
  #      sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
  #   - uses: jetli/wasm-pack-action@v0.4.0
  #     with:
  #       version: 'latest'
  #   - uses: jetli/trunk-action@v0.4.0
  #     with:
  #       version: 'latest'
  #   - name: Build
  #     run: |
  #       cd frontend && trunk build --public-url=/my-web/
  #   - name: cargo fmt & clippy
  #     run: |
  #       cargo fmt --all -- --check
  #       cargo clippy -- --deny=warnings
  #   - name: Run tests
  #     run: |
  #       cd frontend && wasm-pack test --headless --chrome
  #   - name: Deploy demo
  #     uses: JamesIves/github-pages-deploy-action@v4.2.2
  #     with:
  #       branch: gh-pages
  #       folder: crates/conduit-wasm/dist
  #       clean: true

